
[basic]
app_name = Glymage
static_folder = image
static_url = /image
home_page = home.html
# turn off result cache
result_cache_dir = 
# there is no data update step for Glymage
invalidate_cache_on_data_update = false
